//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crystalbyte.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crystalbyte.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToQuickAccess.
        /// </summary>
        public static string AddQuickAccessCommandName {
            get {
                return ResourceManager.GetString("AddQuickAccessCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to quick access.
        /// </summary>
        public static string AddQuickAccessCommandTooltip {
            get {
                return ResourceManager.GetString("AddQuickAccessCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide ribbon. Click on the application bar at the top to display it..
        /// </summary>
        public static string AutoHideRibbonDescription {
            get {
                return ResourceManager.GetString("AutoHideRibbonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-hide ribbon.
        /// </summary>
        public static string AutoHideRibbonTitle {
            get {
                return ResourceManager.GetString("AutoHideRibbonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlendInRibbon.
        /// </summary>
        public static string BlendInRibbonCommandName {
            get {
                return ResourceManager.GetString("BlendInRibbonCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blend in ribbon.
        /// </summary>
        public static string BlendInRibbonCommandTooltip {
            get {
                return ResourceManager.GetString("BlendInRibbonCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string CloseAppMenuCommandName {
            get {
                return ResourceManager.GetString("CloseAppMenuCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseAppMenu.
        /// </summary>
        public static string CloseAppMenuCommandTooltip {
            get {
                return ResourceManager.GetString("CloseAppMenuCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseCommandName {
            get {
                return ResourceManager.GetString("CloseCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseCommandTooltip {
            get {
                return ResourceManager.GetString("CloseCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression is not a property..
        /// </summary>
        public static string ExpressionNotProperty {
            get {
                return ResourceManager.GetString("ExpressionNotProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string MaximizeCommandName {
            get {
                return ResourceManager.GetString("MaximizeCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string MaximizeCommandTooltip {
            get {
                return ResourceManager.GetString("MaximizeCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeCommandName {
            get {
                return ResourceManager.GetString("MinimizeCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeCommandTooltip {
            get {
                return ResourceManager.GetString("MinimizeCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access member in Expression..
        /// </summary>
        public static string NotMemberAccessExpression {
            get {
                return ResourceManager.GetString("NotMemberAccessExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAppMenu.
        /// </summary>
        public static string OpenAppMenuCommandName {
            get {
                return ResourceManager.GetString("OpenAppMenuCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the application menu.
        /// </summary>
        public static string OpenAppMenuCommandTooltip {
            get {
                return ResourceManager.GetString("OpenAppMenuCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE.
        /// </summary>
        public static string OpenAppMenuHeader {
            get {
                return ResourceManager.GetString("OpenAppMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenRibbonOptions.
        /// </summary>
        public static string OpenRibbonOptionsCommandName {
            get {
                return ResourceManager.GetString("OpenRibbonOptionsCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ribbon visibility options.
        /// </summary>
        public static string OpenRibbonOptionsCommandTooltip {
            get {
                return ResourceManager.GetString("OpenRibbonOptionsCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveFromQuickAccess.
        /// </summary>
        public static string RemoveQuickAccessCommandName {
            get {
                return ResourceManager.GetString("RemoveQuickAccessCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from quick access.
        /// </summary>
        public static string RemoveQuickAccessCommandTooltip {
            get {
                return ResourceManager.GetString("RemoveQuickAccessCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreDown.
        /// </summary>
        public static string RestoreDownCommandName {
            get {
                return ResourceManager.GetString("RestoreDownCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore down.
        /// </summary>
        public static string RestoreDownCommandTooltip {
            get {
                return ResourceManager.GetString("RestoreDownCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently displays the ribbons tabs and commands..
        /// </summary>
        public static string ShowTabsAndCommandsDescription {
            get {
                return ResourceManager.GetString("ShowTabsAndCommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs and commands.
        /// </summary>
        public static string ShowTabsAndCommandsTitle {
            get {
                return ResourceManager.GetString("ShowTabsAndCommandsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays only the tabs. Click on a tab to displays its commands..
        /// </summary>
        public static string ShowTabsDescription {
            get {
                return ResourceManager.GetString("ShowTabsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tabs.
        /// </summary>
        public static string ShowTabsTitle {
            get {
                return ResourceManager.GetString("ShowTabsTitle", resourceCulture);
            }
        }
    }
}
